Simplify import completions test
Before: under Py2.7,
`test_should_complete_top_level_modules_for_import` attempts to
complete "import multi" and yields,
```
AssertionError: Lists differ: [file, pledispatch, processing] != [file, processing]
```
because "multipledispatch" is a valid Py2.7 library.

After: simplify test to merely verify "processing" is a valid completion.