Simplify import completions test
Before: `test_should_complete_top_level_modules_for_import` attempts to
complete "import multi" and yields,
```
AssertionError: Lists differ: [file, pledispatch, processing] != [file, processing]
```
because my python installation carries "multipledispatch" as a valid Py2.7 library.

After: simplify test to merely verify "processing" is a valid completion.